Use a glob that allows arbitrary python version numbers.
fedora-python/pyp2rpm pull request #185
Opened 2019-07-03 05:32 UTC by gordonmessmer

If python 3.10 comes after 3.9, the globs used in the templates may break.

2019-07-03 09:09 UTC, hroncok commented
Actually, I prefer `%{python3_version}`. However yes, this is better than status quo.

2019-07-03 09:11 UTC, hroncok commented
Could you try to run tests (with `tox`) and update the expected spec files in [tests/test_data](https://github.com/fedora-python/pyp2rpm/tree/master/tests/test_data)?

2019-07-03 20:13 UTC, gordonmessmer commented
No problem.  We can try this with %{python3_version}.  There are still some tests that don't pass, but those don't seem to be related to this change and we can try to fix them in a later PR.

2019-07-03 21:45 UTC, hroncok requested changes

2019-07-03 21:45 UTC, hroncok commented on pyp2rpm/templates/epel6.spec
> +%{python{{ pv }}_sitearch}/{{ underscored_or_pypi(data.name, data.underscored_name) }}-%{version}-py%{python3_version}-*.pth
This needs to be more clever, see my suggestions for the tests spec files.

2019-07-03 21:45 UTC, hroncok commented on tests/test_data/python-Jinja2_dnfnc.spec
> +%{python2_sitelib}/%{pypi_name}-%{version}-py%{python3_version}.egg-info
```suggestion
%{python2_sitelib}/%{pypi_name}-%{version}-py%{python2_version}.egg-info
```

2019-07-03 21:45 UTC, hroncok commented on tests/test_data/python-Jinja2_epel6_dnfnc.spec
> +%{python2_sitelib}/%{pypi_name}-%{version}-py%{python3_version}.egg-info
```suggestion
%{python2_sitelib}/%{pypi_name}-%{version}-py%{python2_version}.egg-info
```

2019-07-03 21:45 UTC, hroncok commented on tests/test_data/python-Jinja2_epel6_nc.spec
> +%{python2_sitelib}/%{pypi_name}-%{version}-py%{python3_version}.egg-info
```suggestion
%{python2_sitelib}/%{pypi_name}-%{version}-py%{python2_version}.egg-info
```

2019-07-03 21:45 UTC, hroncok commented on tests/test_data/python-Jinja2_epel7_dnfnc.spec
> +%{python2_sitelib}/%{pypi_name}-%{version}-py%{python3_version}.egg-info
```suggestion
%{python2_sitelib}/%{pypi_name}-%{version}-py%{python2_version}.egg-info
```

2019-07-03 21:45 UTC, hroncok commented on tests/test_data/python-Jinja2_epel7_nc.spec
> +%{python2_sitelib}/%{pypi_name}-%{version}-py%{python3_version}.egg-info
```suggestion
%{python2_sitelib}/%{pypi_name}-%{version}-py%{python2_version}.egg-info
```

2019-07-03 21:45 UTC, hroncok commented on tests/test_data/python-Jinja2_mageia_py23.spec
> +%{python2_sitelib}/%{pypi_name}-%{version}-py%{python3_version}.egg-info
```suggestion
%{python2_sitelib}/%{pypi_name}-%{version}-py%{python2_version}.egg-info
```

2019-07-03 21:45 UTC, hroncok commented on tests/test_data/python-Jinja2_nc.spec
> +%{python2_sitelib}/%{pypi_name}-%{version}-py%{python3_version}.egg-info
```suggestion
%{python2_sitelib}/%{pypi_name}-%{version}-py%{python2_version}.egg-info
```

2019-07-03 21:45 UTC, hroncok commented on tests/test_data/python-Jinja2_py23_autonc.spec
> +%{python2_sitelib}/%{pypi_name}-%{version}-py%{python3_version}.egg-info
```suggestion
%{python2_sitelib}/%{pypi_name}-%{version}-py%{python2_version}.egg-info
```

2019-07-03 21:45 UTC, hroncok commented on tests/test_data/python-Jinja2_py2_autonc.spec
> +%{python2_sitelib}/%{pypi_name}-%{version}-py%{python3_version}.egg-info
```suggestion
%{python2_sitelib}/%{pypi_name}-%{version}-py%{python2_version}.egg-info
```

2019-07-03 21:45 UTC, hroncok commented on tests/test_data/python-StructArray_autonc.spec
> +%{python2_sitearch}/%{pypi_name}-%{version}-py%{python3_version}.egg-info
```suggestion
%{python2_sitearch}/%{pypi_name}-%{version}-py%{python2_version}.egg-info
```

2019-07-03 21:45 UTC, hroncok commented on tests/test_data/python-buildkit_autonc.spec
> +%{python2_sitelib}/%{pypi_name}-%{version}-py%{python3_version}.egg-info
```suggestion
%{python2_sitelib}/%{pypi_name}-%{version}-py%{python2_version}.egg-info
```

2019-07-03 21:45 UTC, hroncok commented on tests/test_data/python-sphinx_autonc.spec
> +%{python2_sitelib}/%{pypi_name}-%{version}-py%{python3_version}.egg-info
```suggestion
%{python2_sitelib}/%{pypi_name}-%{version}-py%{python2_version}.egg-info
```

2019-07-03 21:46 UTC, hroncok commented on pyp2rpm/templates/epel6.spec
> +%{python{{ pv }}_sitearch}/{{ underscored_or_pypi(data.name, data.underscored_name) }}-%{version}-py%{python3_version}-*.pth
This is an untested solution:

```suggestion
%{python{{ pv }}_sitearch}/{{ underscored_or_pypi(data.name, data.underscored_name) }}-%{version}-py%{python{{ pv }}_version}-*.pth
```

2019-07-06 20:03 UTC, gordonmessmer commented
I think tests look OK for 3.6, but there are a variety of encoding/locale problems on the other releases.

2019-07-07 00:01 UTC, gordonmessmer commented
The encoding/locale errors can be resolved by installing glibc-langpack-en manually in Dockerfile, though I think its omission from the fedora:rawhide docker image is a bug.  I've filed BZ 1727489 for that.

With that package installed, py35 test seem OK as well.  py27 and py34 fail in pytest, while py37 fails because python package names aren't as expected, but none of those is relevant to this change (AFAIK).

2019-07-08 14:20 UTC, gordonmessmer commented
I've merged the master branch to run the tests again.  I expect them all to complete successfully now except for 3.7 where some package names generated by NameConvertor don't match the expected return value.  I *think* what's happening there is that 3.7 is the only tested release that has the "dnf" module, and that set of tests is trying to find a best-match name in the dnf data.  I'm really unclear on that, but if I'm right I'm not sure how to resolve that problem.

2019-07-08 15:29 UTC, hroncok commented
I still see some "locale.Error: unsupported locale setting". Also, the all the python2-...sphinx... tests make no sense and should be replaced with better examples or xfailed.

2019-07-08 20:30 UTC, gordonmessmer commented
Yes, that's an obscure one.  I suspect (a little) that this is a result of defining "en_US.utf-8" as an alias of "c.utf8" in locale.py.  However, since 3.6 has the same alias, I'm not sure why the problem would only affect 3.7.

2019-07-08 23:21 UTC, gordonmessmer commented
I can recreate the problem now, and it does look like the alias is the cause.  This only affects 3.7 because, again, that's the only one with the "dnf" module.  That module calls "locale.setlocale(locale.LC_ALL, '')" during setup, which changes the locale from C.utf-8 to en_US.utf-8, which is problematic.  I'll have to file a bug against Python for this one...

2019-07-11 18:10 UTC, hroncok commented
BTW:

```
rpm-specs/python-rangehttpserver.spec:%{python3_sitelib}/rangehttpserver-%{version}-py?.?.egg-info
rpm-specs/python-XStatic-mdi.spec:%{python2_sitelib}/XStatic_mdi-%{version}-py?.?.egg-info
rpm-specs/python-XStatic-mdi.spec:%{python3_sitelib}/XStatic_mdi-%{version}-py?.?.egg-info
rpm-specs/python-testing.postgresql.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-libpysal.spec:%{python3_sitelib}/%{srcname}-%{version}-py?.?.egg-info
rpm-specs/mkdocs.spec:%{python3_sitelib}/%{name}-%{version}-py?.?.egg-info
rpm-specs/git-pull-request.spec:%{python3_sitelib}/%{pkg_name}-%{version}-py?.?.egg-info
rpm-specs/python-urlgrabber.spec:%{python2_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-urlgrabber.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-XStatic-Angular-FileUpload.spec:%{python2_sitelib}/XStatic_Angular_FileUpload-%{version}-py?.?.egg-info
rpm-specs/python-XStatic-Angular-FileUpload.spec:%{python3_sitelib}/XStatic_Angular_FileUpload-%{version}-py?.?.egg-info
rpm-specs/python-pipdeptree.spec:%{python3_sitelib}/%{srcname}-%{version}-py?.?.egg-info
rpm-specs/python-jaraco-functools.spec:%{python3_sitelib}/jaraco_functools-%{version}-py?.?.egg-info
rpm-specs/python-h2.spec:%{python2_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-h2.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-ldappool.spec:%{python3_sitelib}/%{srcname}-%{version}-py?.?.egg-info
rpm-specs/python-ldappool.spec:%{python2_sitelib}/%{srcname}-%{version}-py?.?.egg-info
rpm-specs/python-animatplot.spec:%{python3_sitelib}/%{srcname}-%{version}-py?.?.egg-info
rpm-specs/python-testrepository.spec:%{python2_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-testrepository.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-jupyter-core.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-simpleeval.spec:%{python3_sitelib}/%{srcname}-%{version}-py?.?.egg-info/
rpm-specs/python-pytest-expect.spec:%{python3_sitelib}/pytest_expect-%{version}-py?.?.egg-info
rpm-specs/python-qtconsole.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-path.spec:%{python2_sitelib}/path.py-%{version}-py?.?.egg-info/
rpm-specs/python-path.spec:%{python3_sitelib}/path.py-%{version}-py?.?.egg-info/
rpm-specs/python-cligj.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/spec2scl.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-jsonschema.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info/
rpm-specs/python-pykmip.spec:%{python2_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-pykmip.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-auth-credential.spec:%{python3_sitelib}/%{srcname}-%{version}-py?.?.egg-info
rpm-specs/python-yapf.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-minimock.spec:%{python3_sitelib}/MiniMock-%{version}-py?.?.egg-info
rpm-specs/python-dirq.spec:%{python3_sitelib}/%{srcname}-%{version}-py?.?.egg-info
rpm-specs/python-treq.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-pipreqs.spec:%{python3_sitelib}/%{srcname}-%{version}-py?.?.egg-info
rpm-specs/python-pdfminer.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/classification-banner.spec:%{python3_sitelib}/classification_banner-%{version}-py?.?.egg-info
rpm-specs/python-numcodecs.spec:%{python3_sitearch}/%{srcname}-%{version}-py?.?.egg-info
rpm-specs/python-case.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/slack-cleaner.spec:%{python3_sitelib}/%{modname}-%{version}-py?.?.egg-info/
rpm-specs/python-ROPGadget.spec:%{python2_sitelib}/%{srcname}-%{version}-py?.?.egg-info
rpm-specs/python-ROPGadget.spec:%{python3_sitelib}/%{srcname}-%{version}-py?.?.egg-info
rpm-specs/python-xunitmerge.spec:%{python2_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-xunitmerge.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-nose-xcover.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-pathlib2.spec:%{python2_sitelib}/%{modname}-%{version}-py?.?.egg-info
rpm-specs/python-pathlib2.spec:%{python3_sitelib}/%{modname}-%{version}-py?.?.egg-info
rpm-specs/python-tinycss2.spec:%{python3_sitelib}/%{srcname}-%{version}-py?.?.egg-info/
rpm-specs/python-testscenarios.spec:%{python2_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-ghp-import2.spec:%{python3_sitelib}/ghp_import2-%{version}-py?.?.egg-info
rpm-specs/python-defusedxml.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info/
rpm-specs/python-bucky.spec:%{python3_sitelib}/bucky-%{version}-py?.?.egg-info
rpm-specs/python-scrypt.spec:%{python3_sitearch}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-fixtures.spec:%{python2_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-fixtures.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-shellingham.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info/
rpm-specs/python-django-formtools.spec:%{python3_sitelib}/django_formtools-%{version}-py?.?.egg-info
rpm-specs/rdiff-backup.spec:%{python2_sitearch}/rdiff_backup-%{version}-py?.?.egg-info
rpm-specs/python-mtg.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-setuptools-lint.spec:%{python3_sitelib}/setuptools_lint-%{version}-py?.?.egg-info
rpm-specs/python-django-babel.spec:%{python3_sitelib}/django_babel-%{version}-py?.?.egg-info
rpm-specs/python-elephant.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-jupyter-console.spec:%{python3_sitelib}/%{srcname_}-%{version}-py?.?.egg-info
rpm-specs/python-cheroot.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-priority.spec:%{python2_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-priority.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-tomlkit.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/oggconvert.spec:%{python2_sitelib}/oggconvert-%{version}-py?.?.egg-info
rpm-specs/python-incremental.spec:%{python2_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-incremental.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-jinja2.spec:%{python2_sitelib}/Jinja2-%{version}-py?.?.egg-info
rpm-specs/python-jinja2.spec:%{python3_sitelib}/Jinja2-%{version}-py?.?.egg-info
rpm-specs/python-pykdtree.spec:%{python3_sitearch}/%{srcname}-%{version}-py?.?.egg-info
rpm-specs/python-certbot-dns-rfc2136.spec:%{python2_sitelib}/certbot_dns_rfc2136-%{version}-py?.?.egg-info
rpm-specs/python-certbot-dns-rfc2136.spec:%{python3_sitelib}/certbot_dns_rfc2136-%{version}-py?.?.egg-info
rpm-specs/ydiff.spec:%{python3_sitelib}/%{name}-%{version}-py?.?.egg-info
rpm-specs/python-json-logger.spec:%{python3_sitelib}/python_json_logger-%{version}-py?.?.egg-info
rpm-specs/python-requests_ntlm.spec:%{python3_sitelib}/%{srcname}-%{version}-py?.?.egg-info
rpm-specs/python-xtermcolor.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-Naked.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-heapdict.spec:%{python3_sitelib}/%{pkgname}-%{version}-py?.?.egg-info
rpm-specs/python-elpy.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-backcall.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-bash8.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-zeroconf.spec:%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/python-rjsmin.spec:%{python3_sitearch}/%{pypi_name}-%{version}-py?.?.egg-info
rpm-specs/salt-cloud.spec:%{python2_sitelib}/%{eggspace}-%{version} [...]

2019-07-11 19:08 UTC, gordonmessmer commented
Nice.  How'd you generate that list, BTW?  I expected I'd have to clone all of the repositories for everything that creates a python- or python3- package and search them.

2019-07-11 19:40 UTC, hroncok commented
https://pkgs.fedoraproject.org/repo/rpm-specs-latest.tar.xz

Be careful, not only python- or python3- packages are affected.

```
$ repoquery --repo=rawhide -f '*-py3.7.egg-info' --qf "%{NAME}"
```

gives 2550 results, 392 don't match `^python`:

```
$ repoquery --repo=rawhide -f '*-py3.7.egg-info' --qf "%{NAME}" | sort | uniq | grep -v '^python'
alot
ampy
ansible
ansible-bender
antlr4-python3-runtime
apx
artifacts
asciinema
asv
aubio-python3
autoarchive
autokey-common
awscli
bandit
battray
beets
binwalk
black
blivet-gui-runtime
bodhi-server
borgbackup
borgmatic
brd
btest
btrfs-sxbackup
buildbot-master
buildbot-worker
buildbot-www
buildstream
bumpversion
cairo-dock-python3
cantoolz
catfish
ccsm
cekit
ceph-base
cephfs-shell
cinch
classification-banner
cloud-init
codespell
commissaire-client
congruity
copr-cli
copr-keygen
copr-rpmbuild
coreboot-utils
cranc
csvdiff
cxxtest
datagrepper
datanommer
datanommer-commands
ddupdate
deluge-common
devscripts
dib-utils
diceware
diffoscope
diskimage-builder
distgen
docker-compose
doge
dot2tex
dxf2gcode
elastic-curator
electron-cash
electrum
enki
esptool
etckeeper-dnf
execdb
exfalso
fail2ban-server
fedmod
fedora-review
fedpkg
fedscm-admin
flatcam
freeipa-healthcheck
frescobaldi
fros
fusion-icon
gajim
gaupol
gcovr
git-archive-all
git-fame
git-pull-request
git-review
glances
glue
gnofract4d
gnome-gmail
gns3-gui
gns3-net-converter
gns3-server
gpodder
gramps
graphite-api
graphite-web
greenwave
gtimelog
gumbo-parser-python
hashid
hatch
hddfancontrol
heat-cfntools
hgsvn
holland
holland-common
holland-commvault
holland-lvm
holland-mariabackup
holland-mongodump
holland-mysql
holland-mysqldump
holland-mysqllvm
holland-pgdump
holland-xtrabackup
hovercraft
httpie
cheat
chrome-gnome-shell
imagefactory
imagefactory-plugins
inception
initial-setup
ioc-writer
iotop
irclog2html
isrcsubmit
jrnl
kaadbg
kf5-kapidox
khal
khard
kismon
koji-containerbuild
koschei-common
lazygal
lecm
legofy
lightdm-gtk-greeter-settings
limnoria
lorax
lorem-ipsum-generator
lutris
maildirproc
mailman3
mailman3-fedmsg-plugin
manuale
mate-menu
matrix-synapse
meld
menulibre
meson
mgarepo
mingw32-python3-Cython
mingw32-python3-gdal
mingw32-python3-numpy
mingw32-python3-setuptools
mingw64-python3-Cython
mingw64-python3-gdal
mingw64-python3-numpy
mingw64-python3-setuptools
mirrormanager2
mkdocs
mkdocs-alabaster
mkdocs-basic-theme
mkdocs-bootstrap
mkdocs-bootswatch
mkdocs-cinder
mkdocs-material
mlpack-python3
mnemosyne
modtools
module-build-service
mozilla-iot-gateway-addon-python
mu
mycli
mysql-connector-python3
nemo-compare
nemo-emblems
nemo-pastebin
nemo-terminal
netstat-monitor
nfoview
nfs-ganesha-utils
nfsometer
nik4
nml
nodepool
nova-agent
nvmetcli
nyx
ocrmypdf
ogr2osm
onboard
onionshare
OpenLP
openscap-daemon
oraculum
osc
oz
pag
pagure
pagure-dist-git
parsero
pcp2pdf
pcs
pcs-snmp
pdfposter
percol
persepolis
pew
pgzero
photocollage
picard
pintail
pipenv
pipsi
playitagainsam
poezio
polymake-jupyter
porcupine
powerline
printrun-common
proselint
prunerepo
pss
pssh
ptpython3
pybugz
pyflowtools
pyhoca-cli
pyhoca-gui
pychess
PyMca
pymol
pypolicyd-spf
pyppd
pypykatz
pyp2rpm
PySolFC
pysubnettree
pysysbot
PyX
pyzor
py3libacl
py3status
qpid-dispatch-router
qtile
quasselgrep
qutebrowser
ranger
rapid-photo-downloader
rb_libtorrent-python3
RBTools
rebase-helper
recoll
rednotebook
relval
resalloc-openstack
resultsdb
resultsdb_frontend
reuse
rhythmbox-ampache
rmlint
roca-detect
rpkg
rpl
rpmspectool
rst2txt
sagemath-notebook
sagemath-notebook-export
sagemath-sagetex
sasutils
scudcloud
sendKindle
sepolicy_analysis
setconf
setroubleshoot-server
shyaml
simple-ccsm
sos
sos-collector
spec2scl
speedtest-cli
sse2fedmsg
sshuttle
stgit
supervisor
swid-tools
system-config-kdump
system-config-printer-libs
system-storage-manager
systemtap-runtime-python3
s3cmd
targetcli
taskotron-trigger
thefuck
thonny
tito
tldr
todocli
torbrowser-launcher
transifex-client
translate-toolkit
trash-cli
trytond
trytond-account
trytond-account-be
trytond-account-de-skr03
trytond-account-invoice
trytond-account-invoice-history
trytond-account-invoice-line-standalone
trytond-account-product
trytond-account-statement
trytond-account-stock-anglo-saxon
trytond-account-stock-continental
trytond-analytic-account
trytond-analytic-invoice
trytond-analytic-purchase
trytond-analytic-sale
trytond-company
trytond-company-work-time
trytond-country
trytond-currency
trytond-dashboard
trytond-google-maps
trytond-ldap-authentication
trytond-party
trytond-party-siret
trytond-product
trytond-product-cost-fifo
trytond-product-cost-history
trytond-product-price-list
trytond-project
trytond-project-plan
trytond-project-revenue
trytond-purchase
trytond-purchase-invoice-line-standalone
trytond-sale
trytond-sale-opportunity
trytond-sale-price-list
trytond-stock
trytond-stock-forecast
trytond-stock-inventory-location
trytond-stock-location-sequence
trytond-stock-product-location
trytond-stock-supply
trytond-stock-supply-day
trytond-timesheet
tuna
twine
ubertooth-specan-ui
udica
uflash
ufw
urh
urlscan
urlwatch
ursa-major
variety
vault
veusz
vex
vimiv
vint
virt-bootstrap
virtme
virt-who
vitables
waiverdb-common
WALinuxAgent
webtech
wordxtr
wxGlade
xcat
xen
xen-runtime
xonsh
xortool
xpra
yamllint
yawn
yokadi
youtube-dl
Zim
2ping
5minute
```

2019-07-18 17:02 UTC, gordonmessmer commented
I've rebased on the shiny new master.

2019-07-18 18:47 UTC, gordonmessmer commented
Tests look good here, too.  Are there any changes you'd like to see on this PR, before I start suggesting changes to maintainers who have this pattern in their spec files?

2019-07-18 23:59 UTC, hroncok commented
All looks good. I'll recheck tmrw (feel free to bump me if I don't).

Two followup questions:

1. Would you like to co-maintain pyp2rpm an do a new release?

2. How do you plan to proceed with Fedora packages? I can help mass pushing the change if you provide a clever `sed` (or similar).

2019-07-19 05:31 UTC, gordonmessmer commented
> Would you like to co-maintain pyp2rpm an do a new release?

¯\_(ツ)_/¯

Why not?  Sounds awesome.

> How do you plan to proceed with Fedora packages? I can help mass pushing the change if you provide a clever sed (or similar).

Oh good.  I was afraid I'd have to file hundreds of BZ tickets and possibly trigger a rate limiter.

I think this gets 99% of the specs, but it's late and I'll want to go over the diff again tomorrow:

sed -i 's:\(%{python2_site\(lib\|arch\)}/.*-py\)?.?:\1%{python2_version}:; s:\(%{python3_site\(lib\|arch\)}/.*-py\)?.?:\1%{python3_version}:; s:\(%{python3_other_site\(lib\|arch\)}/.*-py\)?.?:\1%{python3_other_version}:' *.spec

2019-07-20 20:04 UTC, gordonmessmer commented
I think the diff of the rpm-spec tree looks good after sed (though, again, there are a handful that probably need manual correction), but it's also 6622 lines long...

I spot-checked the changes by selecting several packages haphazardly, including packages with python2, python3, and python3_other sitelib and archlib, and rebuilding them with their modified spec files:

```#!/bin/bash

while read pkg
do
	fedpkg clone "$pkg"
	pushd "$pkg"
	cp ../rpm-specs-new/"$pkg".spec .
	fedpkg srpm
	mock --rebuild -r epel-7-x86_64 "$pkg"*.src.rpm || exit
	popd
done
```

A few failed during compile and I didn't troubleshoot those further since that didn't seem related to the change I made with sed, but all of the others that I selected built successfully.

2019-07-23 03:52 UTC, gordonmessmer commented
I've modified the remaining spec files and built several of the modified packages in mock for fedora-30-x86_64.

[pyver-specs.txt](https://github.com/fedora-python/pyp2rpm/files/3420111/pyver-specs.txt)

2019-07-23 22:00 UTC, merged