Print logging handlers to stderr on setup.py failure
fedora-python/pyp2rpm pull request #204
Opened 2019-08-01 05:27 UTC by gordonmessmer

2019-08-01 05:29 UTC, gordonmessmer commented
Alternate implementation does not access "logging" module internals.

2019-08-01 09:00 UTC, hroncok commented
I like this one better.

2019-09-28 03:07 UTC, gordonmessmer commented
Is that approval?

2019-09-28 21:26 UTC, hroncok requested changes

2019-09-28 21:26 UTC, hroncok commented on pyp2rpm/metadata_extractors.py
> +            import pyp2rpm.logger
I don't particularly like this import here.

2019-09-29 07:38 UTC, merged